### ISSUE TITLE
关于项目规模和复杂度的问题

### ISSUE THREAD

**Issue by c-rainstorm** [luxiaoxun/NettyRpc#10]
您好，我想将 “分布式 RPC 框架” 作为我的本科毕业设计的题目，但是不太确定规模和复杂度方面是否合适。能否给我一些建议？非常感谢！

**Comment by luxiaoxun** [comment]
看你自己的要求，如果代码你都能看懂并可以演示，也差不多吧

**Comment by c-rainstorm** [comment]
好的，谢谢！
