### ISSUE TITLE
RPCFuture同步器Sync的实现会出现堵塞。

### ISSUE THREAD

**Issue by drisswung** [luxiaoxun/NettyRpc#11]
我的看法是：
`
protected boolean tryRelease(int releases)  {

            if (getState() == pending) {
                if (compareAndSetState(pending, done)) {
                    return true;
                }
                return false;
            } else {
            	return true;
            }
}
`

**Comment by drisswung** [comment]
RPCFuture中的Sync目的应该是获得相应结果后，唤醒wait线程去尝试get结果，但是还需要在获取结果后继续唤醒后续线程，所以state已经为done的话，tryRelease需要返回true

**Comment by luxiaoxun** [comment]
thanks，这样写的确好一点。
