### ISSUE TITLE
为什么不使用对象本身，而要clone()一个对象用于读呢

### ISSUE THREAD

**Issue by yjy1304** [luxiaoxun/NettyRpc#12]
https://github.com/luxiaoxun/NettyRpc/blob/ca90d39c64402d2ae788a7fc5d8746697132dea4/src/main/java/com/nettyrpc/client/ConnectManage.java#L165

**Comment by luxiaoxun** [comment]
再看了一下代码，感觉是没必要这样做，这个ConnectManage写的有点ugly。
