### ISSUE TITLE
RPCFuture起了一个什么样的作用

### ISSUE THREAD

**Issue by chenzhibing** [luxiaoxun/NettyRpc#15]
如题，看了半天源码没太搞懂，如果没有异步回调任务，是不是可以去掉？

**Comment by sMitea** [comment]
Future模式，主要用来做异步回调的

**Comment by bugmakesprogress** [comment]
> 如题，看了半天源码没太搞懂，如果没有异步回调任务，是不是可以去掉？

[如果没有异步回调的话,直接采用最简单的同步方法就行.具体的可以参照](https://my.oschina.net/huangyong/blog/361751)
