### ISSUE TITLE
如果在RpcClientHandler的channelRead0触发之前就调用了rpcFuture.get(),岂不是直接返回null？这逻辑没问题么？

### ISSUE THREAD

**Issue by cysy-lli** [luxiaoxun/NettyRpc#18]
如果在RpcClientHandler的channelRead0触发之前就调用了rpcFuture.get(),岂不是直接返回null？这逻辑没问题么？

**Comment by cysy-lli** [comment]
还有另一个问题，在调用RpcClientHandler.sendRequest()之前，这个channel有可能为空吧，因为channelRegistered是nio的线程处理的，但是sendRequest是main线程处理，虽然一般情况下，channelRegistered是先于sendRequest触发（因为调用sendRequest之前，一般会先调用connect），但是还是存在channel为空的风险吧。。。

**Comment by ygmyth** [comment]
channelRead0触发之前 哪里调用了rpcFuture.get()

**Comment by Sniper2016** [comment]
cysy,你去看get方法，里面是阻塞的，所以不会是null，但是有一丢丢不合理的是没有设置同步超时时间，哈哈

**Comment by luxiaoxun** [comment]
RpcFuture的get支持设置“超时时间”
