### ISSUE TITLE
关于框架设计上的一些错误

### ISSUE THREAD

**Issue by mwq0106** [luxiaoxun/NettyRpc#21]
首先，用了TCP长连接你没有解决TCP黏包的问题吧，高并发下使用同一连接会有问题，其次，对于netty来说，本身其就已经开设了几个线程处理网络请求，你在线程里再开设线程去处理请求这明显违背了netty的设计，本身netty的高性能就与他线程数有关，线程里再开设线程势必会造成性能损失。以上是我看完代码之后的一些想法，有可能说错，欢迎交流

**Comment by luocai** [comment]
有道理诶。。。

**Comment by scn7th** [comment]
> 首先，用了TCP长连接你没有解决TCP黏包的问题吧，高并发下使用同一连接会有问题，其次，对于netty来说，本身其就已经开设了几个线程处理网络请求，你在线程里再开设线程去处理请求这明显违背了netty的设计，本身netty的高性能就与他线程数有关，线程里再开设线程势必会造成性能损失。以上是我看完代码之后的一些想法，有可能说错，欢迎交流

我来交流下：
1. 不会出现所谓TCP黏包问题，Encoder和Decoder是按照header和Body形式读取request和response
2. 工作线程可能是为了完成阻塞线程的操作而设定的，例如数据库读写

**Comment by dengxiangxiang** [comment]
> > 首先，用了TCP长连接你没有解决TCP黏包的问题吧，高并发下使用同一连接会有问题，其次，对于netty来说，本身其就已经开设了几个线程处理网络请求，你在线程里再开设线程去处理请求这明显违背了netty的设计，本身netty的高性能就与他线程数有关，线程里再开设线程势必会造成性能损失。以上是我看完代码之后的一些想法，有可能说错，欢迎交流
> 
> 我来交流下：
> 
> 1. 不会出现所谓TCP黏包问题，Encoder和Decoder是按照header和Body形式读取request和response
> 2. 工作线程可能是为了完成阻塞线程的操作而设定的，例如数据库读写

赞同，netty本身的工作线程不应该进行耗时操作，否则可能阻塞对应eventloop的事件循环

**Comment by bugmakesprogress** [comment]
关于开线程池的问题,知乎这里有个答案可以参考下
Netty中，耗时的业务逻辑代码应该写在哪？ - 郑大侠的回答 - 知乎
https://www.zhihu.com/question/35487154/answer/89255483
