### ISSUE TITLE
RPCFuture 一个疑问

### ISSUE THREAD

**Issue by leetomlee123** [luxiaoxun/NettyRpc#22]
一个request对应一个future
![image](https://user-images.githubusercontent.com/19498940/59999331-4f396b00-9694-11e9-88fe-86bf3f83f6fa.png)
这边的result为什么要用list

**Comment by bugmakesprogress** [comment]
这个list是异步回调函数的列表 不是结果的列表. 你看英文命名就知道了:pendingCallbacks == 可拓展的回调

**Comment by luxiaoxun** [comment]
楼上已经回答了：每个结果future可以添加多个callback回调
