### ISSUE TITLE
RpcClientHandler里的sendRequest方法是不是同步的?

### ISSUE THREAD

**Issue by bugmakesprogress** [luxiaoxun/NettyRpc#28]
我看里面new了个CountDownLatch,然后又执行了await方法阻塞了执行线程,也就是说,不管怎么样,都会同步执行完RPC请求.get里的timeout抛出异常的机制是完全无效的

**Comment by hellochueng** [comment]
我试验了一下，RpcClientHandler里面的countdownlatch是没有意义的，channel.writeAndFlush(request)后面跟监听放行，这个监听方法的作用在发送完消息但是没有接收到返回值后countdown放行，
同步的地方是在获取返回值的时候也就是get方法里面，里面用了aqs阻塞，ClientHandler读取消息后将返回值添加到RPCFuture对象里面在调用done方法对阻塞放行。

**Comment by luxiaoxun** [comment]
这里的CountDownLatch是为了保证client要发送的request一定是发送出去后，再返回一个RPCFuture等结果，如果没有这个“等待”，RPCFuture的get会阻塞netty的IO线程，导致request永远发不出去。
