### ISSUE TITLE
client端RPC调用流程优化

### ISSUE THREAD

**Issue by guoyu09403** [luxiaoxun/NettyRpc#34]
既然有了NettyService注解，是不是可以在客户端调用的过程中，不再使用RpcClient对象来调用，
客户端注入@Autowire RpcClient rpcClient，每次还要create出对应的proxyService。可以用@NettyService解决这个问题。

**Comment by luxiaoxun** [comment]
是个很好的想法，这个项目是自己用来学习的，欢迎pull request。

**Comment by luxiaoxun** [comment]
其实我还想过用spring boot把server和client封装一下，没太多时间搞。

**Comment by guoyu09403** [comment]
> 其实我还想过用spring boot把server和client封装一下，没太多时间搞。

之前用spring boot跑过一次Demo,为了给大家分享RPC知识.
