### ISSUE TITLE
RpcServer实现有问题

### ISSUE THREAD

**Issue by gotZ9** [luxiaoxun/NettyRpc#5]
`RpcServer` 在 `InitializingBean` 接口的实现中阻塞了, 这样会导致 Spring 无法完成初始化.

例如在 `server-spring.xml` 中 `rpcServer` bean的后面添加bean配置, 新添加的bean会无法加载.

**Comment by gotZ9** [comment]
我的想法是将 EventLoopGroup 对象转由外部提供, 也可以自己创建. `RpcServer` 再实现 `DisposableBean` 接口.
```java
@Override
public void afterPropertiesSet() throws Exception {
    if (bossGroup == null) {
        bossGroup = new NioEventLoopGroup();
        bossInitializer = true;
    }
    if (workerGroup == null) {
        workerGroup = new NioEventLoopGroup();
        workerInitializer = true;
    }
    // 略...
}

@Override
public void destroy() throws Exception {
    closeFuture.sync();
    if (bossInitializer) {
        bossGroup.shutdownGracefully();
    }
    if (workerInitializer) {
        workerGroup.shutdownGracefully();
    }
}
```

**Comment by MoXiaoLeng** [comment]
您好  我也遇到这个问题了  能麻烦您发一下这个类怎么改吗

**Comment by MoXiaoLeng** [comment]
我的项目中添加了一些其他的bean之后
现在启动时会卡在这里
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry#getSingleton(java.lang.String, boolean)  方法中的synchronized (this.singletonObjects)  (spring-beans 5.0.0-RELEASE)

**Comment by luxiaoxun** [comment]
个人并不喜欢spring那套东西，server的启动完全可以不用spring。
加了一个类RpcBootstrapWithoutSpring来说明如何不用spring来启动server，代码仅用来学习。

**Comment by bugmakesprogress** [comment]
如果用的是springboot的话,有个更简单的办法: 实现CommandLineRunner接口,在spring的上下文初始化之后回调该接口,实现netty server的初始化.不注意的话我也在这栽了跟头~

**Comment by luxiaoxun** [comment]
已通过一个启动线程来解决该问题
