### ISSUE TITLE
rpc调用有重复2次

### ISSUE THREAD

**Issue by caleimo** [luxiaoxun/NettyRpc#8]
@RpcService(HelloService.class)
public class HelloServiceImpl implements HelloService {
    int a=0;

    @Override
    public String hello(String name) {
        a++;
        System.out.println("调用了"+a);

        return "Hello! " + name;
    }

    @Override
    public String hello(Person person) {
        return "Hello! " + person.getFirstName() + " " + person.getLastName();
    }
}

我将hello方法改了下，看日志发现client请求一次，HelloServiceImpl.hell方法被调用了两次,而且这个方法还有线程同步问题。
调用了1
调用了1
调用了2
调用了3

![image](https://user-images.githubusercontent.com/8202994/31936459-366ec47e-b8e4-11e7-8403-edf1aa4941f1.png)

**Comment by caleimo** [comment]
类 com.nettyrpc.client.RpcClientHandler

public RPCFuture sendRequest(RpcRequest request) {
        final CountDownLatch latch = new CountDownLatch(1);
        RPCFuture rpcFuture = new RPCFuture(request);
        pendingRPC.put(request.getRequestId(), rpcFuture);
        //channel.writeAndFlush(request); #9 注释掉就行了，看下面一行，再次调用了写入了request

        channel.writeAndFlush(request).addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture future) {
                latch.countDown();
            }
        });
        try {
            latch.await();
        } catch (InterruptedException e) {
            LOGGER.error(e.getMessage());
        }

        return rpcFuture;
    }
}

**Comment by luxiaoxun** [comment]
@caleimo 
Thanks, fixed it.
